version: '3'

services:
  web:
    build: .
    command:  sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    expose:
      - 5432

volumes:
  postgres_data: